MAIS15 = {  # Maximaler AIS nach AIS 2015
        "0" : "Unverletzt",
        "1": "Gering",
        "2": "Ernsthaft",
        "3": "Schwer",
        "4": "Sehr Schwer",
        "5": "Kritisch",
        "6": "Maximal (derzeit nicht behandelbar)",
        "9": "Unbekannt"
    }

GESCHL = {  # Geschlecht
        "3": "Männlich",
        "4": "Weiblich",
        "5": "Schwanger",
        "9": "Unbekannt"
    }

ALTER1 = {  # Alter in Jahren
        "0-998": "Tatsächliches Alter",
        "999": "unbekannt"
    }

ALTER2 = {  # Alter in Monaten (bei Alter unter 2 Jahren)
        "0-24": "Alter in Monaten",
        "99": "Unbekannt",
        "0": "Entfällt (Person älter als 2 Jahre)"
    }

BEKLST = {  # Bekleidungsstärke
        "3": "Dünn",
        "4": "Mittel",
        "5": "Dick",
        "8": "Andere",
        "9": "Unbekannt"
    }

FCI = {  # Minimaler FCI
        "1": "FCI 1 (Worst Possible State)",
        "2": "FCI 2 (Severe State)",
        "3": "FCI 3 (Serious State)",
        "4": "FCI 4 (Moderate State)",
        "5": "FCI 5 (Perfect State)",
        "9": "Unbekannt"
    }

ISS15 = {  # Injury Severity Score nach AIS 2015
        "0-99": "Schweregrad-Score",
        "99": "unbekannt"
    }

ART = {  # Art der Verletzung
        "0": "Verletzung o.n.A.",
        "1": "Weichteilverletzung o.n.A.",
        "2": "Haut-/Weichteilprellung",
        "3": "Haut-/Weichteilhämatom",
        "4": "Haut-/Weichteilschürfung",
        "5": "Haut-/Weichteilquetschung",
        "6": "Haut-/Weichteilschnittwunde",
        "7": "Haut-/Weichteil-RQW",
        "8": "Haut-/Weichteilperforation",
        "9": "Haut-/Weichteildecollement",
        "10": "Verbrennung o.n.A.",
        "11": "Verbrennung 1. Grades",
        "12": "Verbrennung 2. Grades",
        "13": "Verbrennung 3. Grades",
        "14": "Verkohlung",
        "20": "Knochenverletzung o.n.A.",
        "21": "Fissur",
        "22": "Fraktur",
        "32": "Defektbruch",
        "33": "Rippenfraktur Einfach",
        "34": "Rippenfraktur (bis 3)",
        "35": "Rippenserienfraktur",
        "42": "Luxationsfraktur",
        "43": "knöcherner Bandausriss",
        "44": "Epiphysenlösung",
        "45": "Epiphysenfraktur",
        "46": "Luxation (Verrenkung)",
        "47": "Amputation",
        "48": "Scharnierfraktur",
        "49": "Distorsion",
        "50": "Organverletzung o.n.A.",
        "51": "Organprellung",
        "52": "Organhämatom",
        "53": "Kapselriss",
        "54": "Organruptur",
        "55": "Organabriss",
        "56": "Organverlust",
        "57": "Organquetschung",
        "60": "Gehirnverletzung o.n.A.",
        "61": "Commotio (SHT 1. Grades)",
        "62": "Contusio (SHT 2. Grades)",
        "63": "Compressio (SHT 3. Grades)",
        "64": "Hämatom (Subdural)",
        "65": "Hämatom (Epidural)",
        "66": "Hirnödem",
        "67": "Subarachnoidalblutung",
        "68": "Intracerebrale Blutung",
        "69": "Ventrikelblutung",
        "70": "Hirnabriss, Austritt",
        "75": "Gefäßverletzung o.n.A.",
        "76": "Gefäßperforation, Einriss",
        "77": "Gefäßdurchtrennung",
        "78": "Intimaverletzung",
        "79": "traumatischer Gefäßverschluss",
        "80": "Bandverletzung o.n.A.",
        "81": "Bandzerrung",
        "82": "Bandruptur /-ausriss",
        "83": "Durchtrennung des Bandes",
        "84": "Durchtrennung der Sehnen",
        "90": "Sehnenverletzung o.n.A.",
        "91": "Sehnenzerrung",
        "92": "Sehnenriss",
        "96": "Verätzung",
        "97": "Zahndefekt",
        "98": "Zahnverlust",
        "99": "Unbekannt"
    }

SITZ_kategorien = {
        "1": "Kopf_Gesicht",
        "2": "Hals",
        "3": "Thorax",
        "4": "Rippen",
        "5": "Abdomen",
        "6": "Becken",
        "7": "Untere Extremitäten",
        "8": "Obere Extremitäten",
        "9": "Allgemein unbekannt"
    }

Kopf_Gesicht = {
        "100": "Kopfverletzung o.n.A.",
        "110": "Knöcherner Schädel o.n.A.",
        "111": "Stirnbein",
        "112": "Schläfenbein",
        "113": "Felsenbein",
        "114": "Nasenbein",
        "115": "Oberkiefer",
        "116": "Unterkiefer",
        "117": "Zähne",
        "118": "Jochbein",
        "119": "Orbita",
        "120": "Knöcherner Gesichtsschädel",
        "121": "Scheitelbein",
        "130": "Schädelbasis o.n.A.",
        "131": "Keilbein",
        "132": "Keilbeinflügel",
        "133": "Vordere Schädelgrube",
        "134": "Hintere Schädelgrube",
        "135": "Foramen Magnum",
        "136": "Knöcherner Hinterkopf",
        "140": "Gehirn o.n.A.",
        "141": "Großhirn",
        "142": "Kleinhirn",
        "143": "Brücke, Stammhirn",
        "144": "Ventrikel",
        "145": "Frontalhirn",
        "146": "Hirnnerven",
        "150": "Weichteil am Kopf",
        "151": "Kopfhaut",
        "152": "Stirn",
        "153": "Augenlid",
        "154": "Nase",
        "155": "Wange",
        "156": "Lippe",
        "157": "Zahnfleisch, Mund",
        "158": "Kinn",
        "160": "Auge o.n.A.",
        "161": "Sclera",
        "162": "Tränenkanal",
        "163": "Aderhaut (Choroidea)",
        "164": "Corpus Ciliaris",
        "165": "Iris",
        "166": "Netzhaut (Retina)",
        "167": "Hornhaut (Cornea)",
        "168": "Nervus Opticus",
        "169": "Humor Aquosus",
        "170": "Corpus Vitreum",
        "171": "Lens",
        "172": "Musculi Bulbi",
        "180": "Ohr o.n.A.",
        "181": "Trommelfell",
        "182": "Innenohr",
        "183": "Mittelohr",
        "184": "Ohrmuschel",
        "185": "Ohrläppchen"
    }

Hals = {
        "200": "Halsverletzung o.n.A.",
        "210": "Halswirbelsäule o.n.A.",
        "211": "C1 - 1. Wirbel",
        "212": "C2 - 2. Wirbel",
        "213": "C3 - 3. Wirbel",
        "214": "C4 - 4. Wirbel",
        "215": "C5 - 5. Wirbel",
        "216": "C6 - 6. Wirbel",
        "217": "C7 - 7. Wirbel",
        "218": "Dens Axis",
        "219": "Bandscheiben",
        "220": "Rückenmark",
        "221": "Nerven/-wurzel",
        "230": "Halsgefäße o.n.A.",
        "231": "Vena Jugularis Externa",
        "232": "Vena Jugularis Interna",
        "233": "Arteria Carotis Interna",
        "234": "Arteria Carotis Communis",
        "240": "Halsorgane o.n.A.",
        "241": "Speiseröhre",
        "242": "Luftröhre",
        "243": "Schilddrüse",
        "244": "Kehlkopf",
        "250": "Weichteile Hals",
        "251": "Halsmuskulatur",
        "252": "Rachen",
        "253": "Schlund",
        "254": "Halsnerven",
        "290": "Zunge",
        "291": "Zungenbein"
    }

Thorax = {
        "300": "Thorax o.n.A.",
        "310": "Brustwirbelsäule o.n.A.",
        "311": "Th1 - 8. Wirbel",
        "312": "Th2 - 9. Wirbel",
        "313": "Th3 - 10. Wirbel",
        "314": "Th4 - 11. Wirbel",
        "315": "Th5 - 12. Wirbel",
        "316": "Th6 - 13. Wirbel",
        "317": "Th7 - 14. Wirbel",
        "318": "Th8 - 15. Wirbel",
        "319": "Th9 - 16. Wirbel",
        "320": "Th10 - 17. Wirbel",
        "321": "Th11 - 18. Wirbel",
        "322": "Th12 - 19. Wirbel",
        "323": "Bandscheibe",
        "324": "Rückenmark",
        "325": "Nerven/-wurzel",
        "330": "Knöcherner Thorax",
        "331": "Clavicula",
        "332": "Sternum",
        "333": "Acromion",
        "334": "Scapula",
        "335": "Acromioclaviculargelenk",
        "336": "Sternoclaviculargelenk",
        "337": "Brustkorb Gesamt",
        "338": "Zwerchfell",
        "340": "Weichteile Thorax",
        "341": "Brustmuskel (Mammae)",
        "342": "Schultermuskulatur",
        "343": "Rückenmuskulatur",
        "344": "Zwischenrippennerven",
        "345": "Sonstige Nerven Thorax",
        "346": "Schulter",
        "347": "Rücken",
        "350": "Herz o.n.A.",
        "351": "Herzbeutel",
        "352": "Herzkranzgefäße",
        "353": "Herzklappen",
        "354": "Septum",
        "355": "Kammer Rechts",
        "356": "Kammer Links",
        "357": "Vorhof Rechts",
        "358": "Vorhof Links",
        "359": "Herzmuskulatur",
        "360": "Lunge o.n.A.",
        "361": "Lungenfell",
        "362": "Bronchus (Groß)",
        "363": "Bronchus (Klein)",
        "364": "Lungengefäß",
        "365": "Oberlappen",
        "366": "Mittellappen",
        "367": "Unterlappen",
        "370": "Thoraxgefäße o.n.A.",
        "371": "Aorta o.n.A.",
        "372": "Aorta Ascendens",
        "373": "Aortenbogen",
        "374": "Aorta Descendens",
        "375": "obere Hohlvene",
        "376": "untere Hohlvene",
        "377": "Arteria Subclavia",
        "378": "Vena Subclavia",
        "379": "Zwischenrippengefäß",
        "380": "Arteria Mammaria Interna",
        "385": "Speiseröhre",
        "390": "Luftröhre",
        "391": "Mediastinum",
        "392": "Thymus"
    }

Rippen = {
        "400": "Rippenfraktur o.n.A.",
        "401": "10., 11. oder 12. Rippe",
        "402": "10. + 11. (11.+ 12.) Rippe",
        "403": "10. - 12. Rippe",
        "411": "1. Rippe",
        "412": "1. + 2. Rippe",
        "413": "1. - 3. Rippe",
        "414": "1. - 4. Rippe",
        "415": "1. - 5. Rippe",
        "416": "1. - 6. Rippe",
        "417": "1. - 7. Rippe",
        "418": "1. - 8. Rippe",
        "419": "1. - 9. (10., 11., 12.) Rippe",
        "421": "2. Rippe",
        "422": "2. + 3. Rippe",
        "423": "2. - 4. Rippe",
        "424": "2. - 5. Rippe",
        "425": "2. - 6. Rippe",
        "426": "2. - 7. Rippe",
        "427": "2. - 8. Rippe",
        "428": "2. - 9. Rippe",
        "429": "2. - 10.(11., 12.) Rippe",
        "431": "3. Rippe",
        "432": "3. + 4. Rippe",
        "433": "3. - 5. Rippe",
        "434": "3. - 6. Rippe",
        "435": "3. - 7. Rippe",
        "436": "3. - 8. Rippe",
        "437": "3. - 9. Rippe",
        "438": "3. - 10. Rippe",
        "439": "3. - 11.(12.) Rippe",
        "441": "4. Rippe",
        "442": "4. + 5. Rippe",
        "443": "4. - 6. Rippe",
        "444": "4. - 7. Rippe",
        "445": "4. - 8. Rippe",
        "446": "4. - 9. Rippe",
        "447": "4. - 10. Rippe",
        "448": "4. - 11. Rippe",
        "449": "4. - 12. Rippe",
        "451": "5. Rippe",
        "452": "5. + 6. Rippe",
        "453": "5. - 7. Rippe",
        "454": "5. - 8. Rippe",
        "455": "5. - 9. Rippe",
        "456": "5. - 10. Rippe",
        "457": "5. - 11. Rippe",
        "458": "5. - 12. Rippe",
        "461": "6. Rippe",
        "462": "6. + 7. Rippe",
        "463": "6. - 8. Rippe",
        "464": "6. - 9. Rippe",
        "465": "6. - 10. Rippe",
        "466": "6. - 11. Rippe",
        "467": "6. - 12. Rippe",
        "471": "7. Rippe",
        "472": "7. + 8. Rippe",
        "473": "7. - 9. Rippe",
        "474": "7. - 10. Rippe",
        "475": "7. - 11. Rippe",
        "476": "7. - 12. Rippe",
        "481": "8. Rippe",
        "482": "8. + 9. Rippe",
        "483": "8. - 10. Rippe",
        "484": "8. - 11. Rippe",
        "485": "8. - 12. Rippe",
        "491": "9. Rippe",
        "492": "9. + 10. Rippe",
        "493": "9. - 11. Rippe",
        "494": "9. - 12. Rippe"
    }

Abdomen = {
        "500": "Abdomen o.n.A.",
        "510": "Lendenwirbelsäule o.n.A",
        "511": "L1 - 20. Wirbel",
        "512": "L2 - 21. Wirbel",
        "513": "L3 - 22. Wirbel",
        "514": "L4 - 23. Wirbel",
        "515": "L5 - 24. Wirbel",
        "516": "Kreuzbein",
        "517": "Steißbein",
        "518": "Bandscheibe",
        "519": "Rückenmark",
        "520": "Cauda Equina / Conus Medullaris",
        "521": "Nerven/-wurzel",
        "530": "Weichteile Abdomen",
        "531": "Bauchmuskulatur",
        "532": "Untere Rückenmuskulatur",
        "533": "Bauchfell",
        "534": "Gekröse (Mesenterium)",
        "535": "Plexus Becken / Sakrum",
        "540": "Abdomengefäße o.n.A.",
        "541": "Aorta Abdominalis",
        "542": "Pfortader",
        "543": "Arteria / Vena Mesenterica",
        "544": "Arteria / Vena Renalis",
        "545": "Milzgefäße",
        "550": "Leber, Galle o.n.A.",
        "551": "Leberkapsel",
        "552": "Leberlappen",
        "553": "Gallenblase",
        "554": "Gallengang",
        "560": "Milz o.n.A.",
        "561": "Milzkapsel",
        "562": "Pankreas o.n.A.",
        "563": "Pankreaskörper",
        "564": "Pankreaskopf",
        "565": "Pankreasschwanz",
        "566": "Ösophagus",
        "570": "Magen o.n.A.",
        "571": "Magen-Fundus",
        "572": "Magen-Corpus",
        "573": "Magen-Antrum",
        "574": "Magen-Pylorus",
        "580": "Darm o.n.A.",
        "581": "Dünndarm, o.n.A.",
        "582": "Duodenum",
        "583": "Jejunum",
        "584": "Ileum",
        "585": "Dickdarm o.n.A.",
        "586": "Colon",
        "587": "Sigma",
        "588": "Rektum",
        "590": "Niere o.n.A.",
        "591": "Nierenbecken",
        "592": "Nierenpol",
        "593": "Nierenkapsel",
        "594": "Ureter",
        "595": "Nebenniere"
    }

Becken = {
        "600": "Becken o.n.A.",
        "610": "Knöchernes Becken",
        "611": "Beckenschaufel",
        "612": "Schambein",
        "613": "Sitzbein",
        "614": "Vorderer Beckenring",
        "615": "Hinterer Beckenring",
        "616": "Symphyse",
        "617": "Acetabulum",
        "618": "Kreuzbein",
        "619": "Steißbein",
        "620": "Ileosacralfuge",
        "630": "Weichteile Becken",
        "631": "Beckenmuskulatur Außen",
        "632": "Beckenmuskulatur Innen",
        "633": "Leistenregion",
        "634": "Blase",
        "635": "Prostata",
        "636": "Nerven Becken",
        "637": "N. Ischiadicus",
        "638": "N. Femoralis",
        "640": "Geschlechtsorgane",
        "641": "Uterus",
        "642": "Eileiter",
        "643": "Eierstöcke",
        "644": "Vagina",
        "645": "Vulva",
        "646": "Penis",
        "647": "Scrotum",
        "648": "Hoden",
        "649": "Labia Majores"
    }

Untere_Extremitäten = {
        "700": "Untere Extremität o.n.A.",
        "710": "Knochen - Beine o.n.A.",
        "711": "Oberschenkel o.n.A.",
        "712": "Hüftkopf",
        "713": "Oberschenkelhals",
        "714": "Oberschenkelschaft",
        "715": "Kondylen",
        "716": "Patella, Knie",
        "717": "Unterschenkel o.n.A.",
        "718": "Wadenbein",
        "719": "Schienbein",
        "720": "Schienbeinkopf",
        "721": "Knöchel",
        "722": "Sprunggelenk",
        "723": "Fuß o.n.A.",
        "724": "Fersenbein",
        "725": "Fußwurzel",
        "726": "Mittelfuß",
        "727": "Zehenknochen",
        "730": "Weichteile Beine",
        "731": "Streckmuskulatur Oberschenkel",
        "732": "Beugemuskel Oberschenkel",
        "733": "Seitenbänder",
        "734": "Kreuzbänder",
        "735": "Meniskus",
        "736": "Wadenmuskulatur",
        "737": "Achillessehne",
        "738": "Fußrücken",
        "739": "Fußsohle",
        "740": "Ferse",
        "741": "Weichteile Zehen",
        "750": "Gefäße Beine",
        "751": "Vena Femoralis",
        "752": "Vena Saphena",
        "753": "Arteria Femoralis",
        "754": "Arteria Poplitea",
        "755": "Unterschenkelgefäße",
        "756": "Fußgefäße o.n.A.",
        "760": "Nerven Beine",
        "761": "Nervus Ischiadicus",
        "762": "Nervus Peroneus",
        "763": "Nervus Tibialis",
        "764": "Nervus Femoralis"
    }

Obere_Extremitäten = {
        "800": "Ubere Extremität o.n.A.",
        "810": "Knochen Obere Extremitäten",
        "811": "Humerus",
        "812": "Ulna",
        "813": "Radius",
        "814": "Radiusköpfchen",
        "815": "Handwurzelknochen",
        "816": "Mittelhandknochen",
        "817": "Fingerknochen",
        "818": "Ellenbogengelenk",
        "819": "Handgelenk",
        "820": "Fingergelenk",
        "821": "Daumengelenk",
        "830": "Weichteile Arme",
        "831": "Oberarm",
        "832": "Ellenbogen",
        "833": "Unterarm",
        "834": "Hand",
        "835": "Handgelenk",
        "836": "Finger",
        "840": "Gefäße Arme",
        "841": "Vena Axillaris",
        "842": "Vena Cephalica",
        "843": "Vena Basilica",
        "844": "Arteria Brachialis",
        "845": "Arteria Cubitalis",
        "846": "Arteria Radialis",
        "847": "Arteria Ulnaris",
        "850": "Nerven Arme",
        "851": "Nervus Ulnaris",
        "852": "Nervus Radialis",
        "853": "Nervus Medianus",
        "854": "oberer Armplexus",
        "855": "unterer Armplexus",
        "856": "Hautnerven Oberarm",
        "857": "Hautnerven Unterarm",
        "858": "Fingernerven"
    }

unbekannt = {
        "999": "Unbekannt"
    }

AIS15 = {  # Verletzungsschweregrad nach AIS2015
        "1": "Gering",
        "2": "Ernsthaft",
        "3": "Schwer",
        "4": "Sehr Schwer",
        "5": "Kritisch",
        "6": "Maximal (Derzeit nicht Behandelbar)",
        "9": "Nicht Angegeben"
    }

RELI = {  # rechts - links
        "0": "Nicht Angegeben",
        "1": "Rechts",
        "2": "Links",
        "9": "Unbekannt"
    }

VORNHINT = {  # vorn - hinten
        "0": "Nicht Angegeben",
        "1": "Vorn, Ventral",
        "2": "Hinten, Dorsal",
        "3": "Zirkulär",
        "9": "Unbekannt"
    }

PRODI = {  # proximal - distal
        "0": "Nicht Angegeben",
        "1": "Proximal",
        "2": "Distal",
        "3": "Mittleres Drittel",
        "4": "Ganze Extremität",
        "9": "Unbekannt"
    }

INNEN = {  # innen - außen
        "0": "entfällt (nicht Extremitäten)",
        "1": "Nicht Angegeben",
        "2": "Innen / Medial",
        "3": "Außen / Lateral",
        "4": "Mitte / Zirkulär",
        "5": "Zirkulär",
        "9": "Unbekannt"
    }

PSKZ = {  # Positionskennzeichen
     "1" : "PKW - Fahrer",
"2" : "PKW - Beifahrer", 
"3" : "PKW - Insassen Hinten Links", 
"4" : "PKW - Insasse Hinten Rechts", 
"5" : "PKW - Insasse Hinten Mitte", 
"6" : "PKW - Insasse Vorn Mitte", 
"7" : "PKW - Insasse 3. Reihe Kinks", 
"8" : "PKW - Insasse 3. Reihe Rechts", 
"9" : "PKW - Insasse 3. Reihe Mitte", 
"10": "PKW - Insassen (Position unbekannt)",
"11": "PKW - Insassen (Position unbekannt)",
"12": "PKW - Insassen (Position unbekannt)",
"13": "PKW - Insassen (Position unbekannt)",
"14": "PKW - Insassen (Position unbekannt)",
"15": "PKW - Insassen (Position unbekannt)",
"16": "PKW - Insassen (Position unbekannt)",
"17": "PKW - Insassen (Position unbekannt)",
"18": "PKW - Insassen (Position unbekannt)",
"19" : "PKW - Insassen (Position unbekannt)",
"20" : "Insasse Wohnbereich Wohnwagen", 
"25": "Insassen im PKW-Anhänger",
"26": "Insassen im PKW-Anhänger",
"27": "Insassen im PKW-Anhänger",
"28": "Insassen im PKW-Anhänger",
"29" : "Insassen im PKW-Anhänger",
"31" : "Zweiradfahrer", 
"32" : "Zweiradsozius Hinten", 
"33" : "Zweiradsozius Mitte (Kind in Kindersitz)", 
"34" : "Zweiradsozius Beiwagen", 
"35": "Person im Zweirad-Anhänger", 
"36": "Person im Zweirad-Anhänger", 
"37": "Person im Zweirad-Anhänger", 
"38" : "sonst. Zweiradbenutzer", 
"39" : "Zweiradbenutzer (Position Unbekannt)", 
"40" : "Fußgänger", 
"50" : "LKW-Insasse vorn Mitte", 
"51" : "LKW- bzw. Bus-Fahrer", 
"52" : "LKW/Bus - Beifahrer",
"53" : "Verletzte Bus/Bahn/LKW-Insassen", 
"54": "Verletzte Bus/Bahn/LKW-Insassen", 
"55": "Verletzte Bus/Bahn/LKW-Insassen", 
"56": "Verletzte Bus/Bahn/LKW-Insassen", 
"57": "Verletzte Bus/Bahn/LKW-Insassen", 
"58": "Verletzte Bus/Bahn/LKW-Insassen", 
"59": "Verletzte Bus/Bahn/LKW-Insassen", 
"60": "Verletzte Bus/Bahn/LKW-Insassen", 
"61": "Verletzte Bus/Bahn/LKW-Insassen", 
"62": "Verletzte Bus/Bahn/LKW-Insassen", 
"63": "Verletzte Bus/Bahn/LKW-Insassen", 
"64": "Verletzte Bus/Bahn/LKW-Insassen", 
"65": "Verletzte Bus/Bahn/LKW-Insassen", 
"66": "Verletzte Bus/Bahn/LKW-Insassen", 
"67": "Verletzte Bus/Bahn/LKW-Insassen", 
"68": "Verletzte Bus/Bahn/LKW-Insassen", 
"69": "Verletzte Bus/Bahn/LKW-Insassen", 
"70": "Verletzte Bus/Bahn/LKW-Insassen", 
"71": "Verletzte Bus/Bahn/LKW-Insassen", 
"72": "Verletzte Bus/Bahn/LKW-Insassen", 
"73": "Verletzte Bus/Bahn/LKW-Insassen", 
"74": "Verletzte Bus/Bahn/LKW-Insassen", 
"75": "Person im LKW-Anhänger",
"76": "Person im LKW-Anhänger",
"77": "Person im LKW-Anhänger",
"78": "Person im LKW-Anhänger",
"79": "Person im LKW-Anhänger",
"80": "Person im LKW-Anhänger" 
    }
FCI15 = {  # Functional Capacity Index nach AIS2015
        "0-9": "Functional Capacity Index Wert für Einschränkungen"
    }
